In [41]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [9]:
# printing the stopword in english
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [11]:
dataset = pd.read_csv("dataset.csv")

In [ ]:
# checking no of rows and columns
dataset.shape

(72134, 4)

In [ ]:
# printing first 5 rows of dataset
dataset.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [14]:
# printing last 5 rows of dataset
dataset.tail()

,Unnamed: 0,title,text,label
72129,72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
72131,72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
72132,72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
72133,72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [15]:
# counting the number of missing values in the dataset
dataset.isnull().sum()

Unnamed: 0      0
title         558
text           39
label           0
dtype: int64

In [16]:
# replacing the null values with empty string
dataset = dataset.fillna('')

In [25]:
# merging the title and text column
dataset['content'] = dataset['title']

In [26]:
print(dataset['content'])

0        LAW ENFORCEMENT ON HIGH ALERT Following Threat...
1
2        UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3        Bobby Jindal, raised Hindu, uses story of Chri...
4        SATAN 2: Russia unvelis an image of its terrif...
                               ...
72129    Russians steal research on Trump in hack of U....
72130     WATCH: Giuliani Demands That Democrats Apolog...
72131    Migrants Refuse To Leave Train At Refugee Camp...
72132    Trump tussle gives unpopular Mexican leader mu...
72133    Goldman Sachs Endorses Hillary Clinton For Pre...
Name: content, Length: 72134, dtype: str

In [27]:
# separating the features and the target
X = dataset.drop(
    'label',
    axis = 1
)
Y = dataset['label']

In [28]:
print(X)

       Unnamed: 0                                              title  \
0               0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...
1               1
2               2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3               3  Bobby Jindal, raised Hindu, uses story of Chri...
4               4  SATAN 2: Russia unvelis an image of its terrif...
...           ...                                                ...
72129       72129  Russians steal research on Trump in hack of U....
72130       72130   WATCH: Giuliani Demands That Democrats Apolog...
72131       72131  Migrants Refuse To Leave Train At Refugee Camp...
72132       72132  Trump tussle gives unpopular Mexican leader mu...
72133       72133  Goldman Sachs Endorses Hillary Clinton For Pre...

                                                    text  \
0      No comment is expected from Barack Obama Membe...
1         Did they post their votes for Hillary already?
2       Now, most of the demonstrators gathered last ...
3      A dozen politically active pastors came here f...
4      The RS-28 Sarmat missile, dubbed Satan 2, will...
...                                                  ...
72129  WASHINGTON (Reuters) - Hackers believed to be ...
72130  You know, because in fantasyland Republicans n...
72131  Migrants Refuse To Leave Train At Refugee Camp...
72132  MEXICO CITY (Reuters) - Donald Trump’s combati...
72133  Goldman Sachs Endorses Hillary Clinton For Pre...

                                                 content
0      LAW ENFORCEMENT ON HIGH ALERT Following Threat...
1
2      UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3      Bobby Jindal, raised Hindu, uses story of Chri...
4      SATAN 2: Russia unvelis an image of its terrif...
...                                                  ...
72129  Russians steal research on Trump in hack of U....
72130   WATCH: Giuliani Demands That Democrats Apolog...
72131  Migrants Refuse To Leave Train At Refugee Camp...
72132  Trump tussle gives unpopular Mexican leader mu...
72133  Goldman Sachs Endorses Hillary Clinton For Pre...

[72134 rows x 4 columns]

In [29]:
print(Y)

0        1
1        1
2        1
3        0
4        1
        ..
72129    0
72130    1
72131    0
72132    0
72133    1
Name: label, Length: 72134, dtype: int64

In [30]:
# performing stemming
port_stem = PorterStemmer()

In [31]:
def stemming(content):
    stemmed_content = re.sub(
        '[^a-zA-Z]',
        ' ',
        content
    )
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [
        port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')
    ]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

In [32]:
dataset['content'] = dataset['content'].apply(stemming)

In [33]:
print(dataset['content'])

0        law enforc high alert follow threat cop white ...
1
2        unbeliev obama attorney gener say charlott rio...
3        bobbi jindal rais hindu use stori christian co...
4        satan russia unv imag terrifi new supernuk wes...
                               ...
72129    russian steal research trump hack u democrat p...
72130    watch giuliani demand democrat apolog trump ra...
72131         migrant refus leav train refuge camp hungari
72132    trump tussl give unpopular mexican leader much...
72133           goldman sach endors hillari clinton presid
Name: content, Length: 72134, dtype: str

In [34]:
# separating features and target
X = dataset['content'].values
Y = dataset['label'].values

In [35]:
print(X)

<StringArray>
[              'law enforc high alert follow threat cop white blacklivesmatt fyf terrorist video',
                                                                                               '',
 'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video',
                    'bobbi jindal rais hindu use stori christian convers woo evangel potenti bid',
                            'satan russia unv imag terrifi new supernuk western world take notic',
                                         'time christian group sue amazon splc design hate group',
                              'dr ben carson target ir never audit spoke nation prayer breakfast',
                                      'hous intel chair trump russia fake stori evid anyth video',
           'sport bar owner ban nfl game show true american sport like speak rural america video',
                                     'latest pipelin leak underscor danger dakota access pipelin',
 ...
                                         'unlik contend rise franc antithesi trump new york time',
                                          'wow jill stein firesid chat expos delus recount video',
                                                     'determin kill tough gun law end mass shoot',
             'wikileak email show clinton foundat fund use lavish wed spoil brat chelsea clinton',
                           'judg jeanin sound free speech alarm tri silenc time fight back video',
                                             'russian steal research trump hack u democrat parti',
                                     'watch giuliani demand democrat apolog trump racist birther',
                                                   'migrant refus leav train refuge camp hungari',
                                   'trump tussl give unpopular mexican leader much need shot arm',
                                                     'goldman sach endors hillari clinton presid']
Length: 72134, dtype: str

In [36]:
print(Y)

[1 1 1 ... 0 0 1]

In [44]:
# converting textual data into numerical data
vectorizer = TfidfVectorizer()
vectorizer.fit(X)

X = vectorizer.transform(X)
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 629110 stored elements and shape (72134, 19639)>
  Coords	Values
  (0, 407)	0.3190180925014663
  (0, 1802)	0.33473541566384035
  (0, 3679)	0.24871262252022117
  (0, 5509)	0.31820565801047196
  (0, 6425)	0.28932771754845743
  (0, 6730)	0.48553136502134386
  (0, 7887)	0.26746434949988324
  (0, 9699)	0.22829788917209384
  (0, 17260)	0.24871262252022117
  (0, 17363)	0.2542650376115143
  (0, 18648)	0.1297506867782943
  (0, 19106)	0.19134939529376566
  (2, 1049)	0.28404017886581956
  (2, 2673)	0.30809679188606154
  (2, 2919)	0.3639616996972358
  (2, 6880)	0.2652283770602196
  (2, 8020)	0.2692285294185893
  (2, 11864)	0.2231406266784195
  (2, 12011)	0.16878852994653004
  (2, 12744)	0.27904818164471595
  (2, 13591)	0.22687620695463123
  (2, 14591)	0.3580030298678158
  (2, 15094)	0.1609967301122813
  (2, 16446)	0.1999703023632961
  (2, 18034)	0.35962437110547785
  :	:
  (72130, 17778)	0.13227219506940732
  (72130, 18936)	0.25302499393443006
  (72131, 2566)	0.3967249021272091
  (72131, 8206)	0.46269177743112333
  (72131, 9752)	0.3384827653769501
  (72131, 10933)	0.35527231533143033
  (72131, 14182)	0.32391500471431983
  (72131, 14186)	0.3534104623564766
  (72131, 17617)	0.39738745004026604
  (72132, 873)	0.3038308430269035
  (72132, 7003)	0.2582870894160619
  (72132, 9731)	0.24522811865098657
  (72132, 10871)	0.3272655004229104
  (72132, 11350)	0.32005174915301016
  (72132, 11617)	0.2703806807329965
  (72132, 15632)	0.30543362821165165
  (72132, 17778)	0.10874560860578947
  (72132, 17906)	0.4674560433180039
  (72132, 18264)	0.417810680338284
  (72133, 3245)	0.26228453414449976
  (72133, 5498)	0.4224992179824501
  (72133, 7103)	0.5410264267527618
  (72133, 7904)	0.2573590839479994
  (72133, 13427)	0.29001763267842906
  (72133, 14901)	0.5564599843232266

In [45]:
# splitting the dataset into testing and training data
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size = 0.2,
    stratify = Y,
    random_state = 2
)

In [46]:
# model training
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [48]:
# model evaluation
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(
    X_train_prediction,
    Y_train
)
print("Accuracy score of the training data: ", training_data_accuracy)

X_test_prediction = model.predict(X_test)
testing_data_accuracy = accuracy_score(
    X_test_prediction,
    Y_test
)
print("Accuracy score of the training data: ", testing_data_accuracy)

Accuracy score of the training data:  0.9193858630668723
Accuracy score of the training data:  0.900603035974215